### ISSUE TITLE
Crash sur toutes les sorties

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#246]
Erreur PHP:
```
[Sat Sep  2 21:32:05 2017] PHP Fatal error:  Uncaught TypeError: Return value of insert_sortie() must be of the type array, integer returned in /home/darnuria/Oressource/oressource/core/requetes.php:572
Stack trace:
#0 /home/darnuria/Oressource/oressource/api/sorties.php(85): insert_sortie(Object(PDO), Array)
#1 {main}
  thrown in /home/darnuria/Oressource/oressource/core/requetes.php on line 572
[Sat Sep  2 21:32:05 2017] ::1:58928 [200]: /api/sorties.php - Uncaught TypeError: Return value of insert_sortie() must be of the type array, integer returned in /home/darnuria/Oressource/oressource/core/requetes.php:572
Stack trace:
#0 /home/darnuria/Oressource/oressource/api/sorties.php(85): insert_sortie(Object(PDO), Array)
#1 {main}
  thrown in /home/darnuria/Oressource/oressource/core/requetes.php on line 572
```

**Comment by darnuria** [comment]
Correctif dans #247

**Comment by darnuria** [comment]
@mart1ver le correctif est dans #
