### ISSUE TITLE
bug (discret mais bien reel) dans ifaces/modification_verif_sorties.php

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#399]
seuls les dons simples sont pris en charge, le cas des 4 autre classes de sorties hors boutique nous mene à une modification de sortie non approprié

**Comment by darnuria** [comment]
J'ai du reinstaller tout en septembre car mon Thinkpad x250 est mort... :(
Du coup je repars avec une base fraiche, je je vais reprendre une vielle base de la RCK pour tenter de reproduire la configuration que tu as @mart1ver. Problablement j'ai le temps entre maintenant et dimanche prochain la période est terrible l'impression de courir partout.

Si tu peux me lacher une capture d'ecran, des log ou comment reproduire, ça me fera gagner du temps ! :)

**Comment by darnuria** [comment]
```
[Sun Oct 18 18:05:18 2020] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/darnuria/Oressource/oressource/api/sorties.php on line 184
[Sun Oct 18 18:05:18 2020] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`oressource`.`pesees_sorties`, CONSTRAINT `FK_PeseesSorties_TypeDechets` FOREIGN KEY (`id_type_dechet`) REFERENCES `type_dechets` (`id`)) in /home/darnuria/Oressource/oressource/api/sorties.php:75
Stack trace:
#0 /home/darnuria/Oressource/oressource/api/sorties.php(75): PDOStatement->execute()
#1 /home/darnuria/Oressource/oressource/api/sorties.php(200): insert_pesee_sortie()
#2 {main}
  thrown in /home/darnuria/Oressource/oressource/api/sorties.php on line 75
[Sun Oct 18 18:05:18 2020] 127.0.0.1:40872 [500]: POST /api/sorties.php - Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`oressource`.`pesees_sorties`, CONSTRAINT `FK_PeseesSorties_TypeDechets` FOREIGN KEY (`id_type_dechet`) REFERENCES `type_dechets` (`id`)) in /home/darnuria/Oressource/oressource/api/sorties.php:75
Stack trace:
#0 /home/darnuria/Oressource/oressource/api/sorties.php(75): PDOStatement->execute()
#1 /home/darnuria/Oressource/oressource/api/sorties.php(200): insert_pesee_sortie()
#2 {main}
  thrown in /home/darnuria/Oressource/oressource/api/sorties.php on line 75
```

A eplucher

**Comment by darnuria** [comment]
C'etait des typo. PHP c'est juste yew.

**Comment by darnuria** [comment]
Fixé je pense besoin d'un retour d'usage je close en attendant.
