### ISSUE TITLE
Crash des sorties si pas de localités dans la base

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#406]
## Comment reproduire

Installer Oressource de 0; utiliser la base d'exemple `mysql/Oressource.sql`:

- Enregistrez un point de sortie
- enregistrez un type de poubelle
- saisissiez une sortie poubelle
```
#2 {main}
  thrown in /home/darnuria/Oressource/oressource/api/sorties.php on line 144
[Sun Oct 18 17:36:44 2020] 127.0.0.1:38072 [500]: POST /api/sorties.php - Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`oressource`.`sorties`, CONSTRAINT `FK_Sorties_Localites` FOREIGN KEY (`id_point_sortie`) REFERENCES `localites` (`id`)) in /home/darnuria/Oressource/oressource/api/sorties.php:144
Stack trace:
#0 /home/darnuria/Oressource/oressource/api/sorties.php(144): PDOStatement->execute()
#1 /home/darnuria/Oressource/oressource/api/sorties.php(183): insert_sortie()
#2 {main}
  thrown in /home/darnuria/Oressource/oressource/api/sorties.php on line 144
```
Reponse du serveur
```
{"error":"Une erreur est survenue dans Oressource vente annul\u00e9e."}
```
## Resolution

Oups! Un petit update lié a un champ `localite` sur les `sorties` qui sert actuellement a rien... Je vais le supprimer je pense. :)

**Comment by darnuria** [comment]
Fix en cours.
